duration: 5
countLimit: 1
rateLimit: 0
errorList:
    - "ERROR"
    - "WARNING"
topic: "purchases"
kafkaPropertiesPath: "src/main/resources/configs/prop.properties"
kafkaGroupIdConfig: "kafka-java-getting-started"
kafkaAutoOffsetResetConfig: "earliest"
